### ISSUE TITLE
TS seems to be misaligned

### ISSUE THREAD

**Issue by frostschutz** [petrkutalek/telxcc#10]
I tried your program, with *.ts files produced by my Comag SL-40 HD Receiver. It complains about every TS packet being misaligned by 4 bytes and produces no output.

For some strange reason, it works when changing the TS_PACKET_SIZE to 196.

<pre>#define TS_PACKET_SIZE 196</pre>

It still complains about the first TS packet then but it produces the proper name, date and subtitles.

**Comment by petrkutalek** [comment]
@frostschutz Please, could you provide me with such TS files?

**Comment by frostschutz** [comment]
http://metamorpher.de/files/data0001.ts.xz

**Comment by petrkutalek** [comment]
Your file is not a Transport Stream file, it is a BDAV MPEG-2 Transport Stream. Please, see ```-m``` command line switch: -m = input file format is BDAV MPEG-2 Transport Stream (BluRay and some IP-TV recorders).

```
$ telxcc -m -t 8192 -v -i data0001.ts > data0001.srt
telxcc - TELeteXt Closed Captions decoder
(c) Forers, s. r. o., <info@forers.com>, 2011-2014; Licensed under the GPL.
Version 2.6.0 (Apple), Built on Feb  4 2015

- Processing input stream as a BDAV MPEG-2 Transport Stream
- No teletext PID specified, first received suitable stream PID is 6530 (0x1982), not guaranteed
- PID 0xbd PTS available
- Programme Identification Data = Hinter den Fassaden 
- Programme Timestamp (UTC) = Tue Jan  6 12:09:17 2015
- Transmission mode = serial
- No teletext page specified, first received suitable page is 777, not guaranteed
- Using G0 Latin National Subset ID 0x0.4 (German)
- There were some CC data carried via pages = 777 
- Done (6492 teletext packets processed, 9 frames produced)

$ 
```

**Comment by frostschutz** [comment]
That's great to know, thanks. From reading the `-h`, this option didn't catch my eye since my sat reciever is neither bluray nor iptv related. It's a regular, very cheap sat receiver (it was like 20-30€).

I'm not familiar with the file format at all... is there no way to detect this case? Currently every output made by the program (if not aware of this option) suggests an error of some kind.

Thanks again for this; I've had this receiver for years and only now found such a great way to get at the title of the recording as well as its subtitles.

**Comment by petrkutalek** [comment]
Good point, I will update ```-h``` hint text in the release v3.0.0.

(TV Channels are broadcasted in the form of Transport Streams — data streames packetized into chunks of 188 bytes. Bluray and some HD devices etc. use BDAV MPEG-2 Transport Stream, that's almost the same, nevertheless packets are 192 bytes long — 4 bytes prepended to TS packets contain timestamp that helps seeking in Bluray and HD camcoders.)
