### ISSUE TITLE
Make problems

### ISSUE THREAD

**Issue by ggodart** [petrkutalek/telxcc#9]
Latest commit fails during make with Mingw;

gcc -c -std=gnu99 -O3 -Wall -pedantic -o telxcc.o telxcc.c
telxcc.c: In function 'main':
telxcc.c:1097:3: warning: implicit declaration of function 'GetConsoleWindow' [-Wimplicit-function-d
eclaration]
   HWND consoleWnd = GetConsoleWindow();
   ^
telxcc.c:1097:21: warning: initialization makes pointer from integer without a cast [enabled by defa
ult]
   HWND consoleWnd = GetConsoleWindow();
                     ^
windres -J rc -O coff -o telxcc.res telxcc.rc
gcc -o telxcc.exe telxcc.o telxcc.res -lcomctl32
telxcc.o:telxcc.c:(.text.startup+0x1004): undefined reference to `GetConsoleWindow'
collect2.exe: error: ld returned 1 exit status
Makefile.win:18: recipe for target 'telxcc.exe' failed
mingw32-make: *** [telxcc.exe] Error 1

am I missing something?

Thanks

**Comment by petrkutalek** [comment]
I will check this issue at the end of this week as I do not have access to my Windows devel platform at the moment. Reminder created.

**Comment by ggodart** [comment]
THX Petr
It makes fine on Mac
Giles

**Comment by darealshinji** [comment]
I did a quick lookup and it seems that you have to define _WIN32_WINNT as >= 0x0500 somewhere.
Can you check if the following works?
```
gcc -c -std=gnu99 -O3 -Wall -pedantic -D_WIN32_WINNT=0x0500 -o telxcc.o telxcc.c
windres -J rc -O coff -o telxcc.res telxcc.rc
gcc -o telxcc.exe telxcc.o telxcc.res -lcomctl32
```

**Comment by ggodart** [comment]
Thanks Petre

I’m travelling today so only have Mac - will try on windows tomorrow 

Giles

**Comment by ggodart** [comment]
Yes, that fixed it - thanks

Giles

**Comment by petrkutalek** [comment]
Well, @darealshinji is right, you have to define ```_WIN32_WINNT``` by using the ```#define``` statement in the source file, or by specifying the ```-D``` compiler option:  
```
CCFLAGS = -std=gnu99 -O3 -Wall -pedantic -D_WIN32_WINNT=0x0501
```

**Comment by ggodart** [comment]
THX Petr

Giles
